### ISSUE TITLE
stuck on the 2nd path to downloading deaflingo

### ISSUE THREAD

**Issue by lubbydoo** [MHS-Math-Club/Deaflingo#13]
Hi, I recently just saw a yt vid abt this and decided to download it to give it a try. However, through my path in downloading it, I come across the part where I need to run "git lfs install". My question is just on where I shld run this lol. Any help would be much appreciated :) .

**Comment by ghost** [comment]
You would run it in your terminal environment where you plan to run Deaflingo. Unfortunately as of now you won't be able to clone the files via Git LFS since we have exceeded our data quota.
