### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by macy-k** [MHS-Math-Club/Deaflingo#9]
Hello! I saw your Youtube video and this project looks really cool! I've followed the steps in your ReadMe, but I end up with this error when I try to run the `python app.py`:
```
Traceback (most recent call last):
File "C:\Users\macyk\Downloads\Deaflingo-main\app.py", line 13, in <module>
    model_dict = pickle.load(open('./model.p', 'rb'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.
```
I also set up a venv then tried again and got the same error. Any advice?

**Comment by ghost** [comment]
Apologies for the oversight. I forgot to mention in the readme that you'll need Git LFS.

To rectify this:

1. Delete the cloned project.
2. Install [Git LFS](https://git-lfs.com/).
3. Set up Git LFS for your user account by running: `git lfs install`.
4. Finally, clone the project again.

**Comment by GeorgeAzma** [comment]
Cool project, though I couldn't download it because Git LFS is out of bandwidth.
Each git clone of data.pickle and model.p seems to be ~230MB of bandwidth 
and it costs $5/month for 50GiB (or ~53.7GB) so $5/month for ~233 clones.

Though you can also split large files into chunks of 100MiB (maybe it's 50MiB)
because git has file size limit of 100MiB but repository limit of 10GiB

```
Downloading data.pickle (60 MB)
Error downloading object: data.pickle (fdb500c): Smudge error: Error downloading data.pickle (fdb500c8276495910bc9801524fb452d5e1d9eaf25ec2b403b8e04b458524418): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by flyinggoatman** [comment]
> Cool project, though I couldn't download it because Git LFS is out of bandwidth. Each git clone of data.pickle and model.p seems to be ~230MB of bandwidth and it costs $5/month for 50GiB (or ~53.7GB) so $5/month for ~233 clones.
> 
> Though you can also split large files into chunks of 100MiB (maybe it's 50MiB) because git has file size limit of 100MiB but repository limit of 10GiB
> 
> ```
> Downloading data.pickle (60 MB)
> Error downloading object: data.pickle (fdb500c): Smudge error: Error downloading data.pickle (fdb500c8276495910bc9801524fb452d5e1d9eaf25ec2b403b8e04b458524418): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> ```
Is this on our end or the developers?

**Comment by LounaCodes** [comment]
Same problem here, this is part of the response I get, so it might be on the devs?
`Error downloading object: data.pickle (fdb500c): Smudge error: Error downloading data.pickle (fdb500c8276495910bc9801524fb452d5e1d9eaf25ec2b403b8e04b458524418): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

**Comment by ghost** [comment]
I have added a notice on the readme identifying the issue for now. We are looking at possible options for the future of Deaflingo currently so we have not paid for more storage or bandwidth yet. In the future we would run the model via an external server so this won't be an issue.
